version: "3.7"
services:
  server:
    container_name: server_as_ctn
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${PORT}:1001
    depends_on:
      - db
    env_file:
      - ./src/.envs/.prod.env
      
  db:
    hostname: "postgres"
    image: "postgres:latest"
    container_name: "db_as_ctn"
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:5432
    env_file:
      - ./src/.envs/.prod.env
 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
