version: "3.7"
services:
  server:
    container_name: server_as_ctn
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 1001:1001
    depends_on:
      - db
    env_file:
      - .env
      
  db:
    hostname: "postgres"
    image: "postgres:latest"
    container_name: "db_as_ctn"
    restart: always
    environment:
      POSTGRES_DB: another_story
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
